apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-deployment
  labels:
    app: ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
        - name: ci-cd-app-container
          image: your-dockerhub-username/ci-cd-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000   # backend port from your Node.js server
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 4000        # service port
      targetPort: 4000  # container port
      nodePort: 30080   # external port (http://localhost:30080)
