apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 4000       # inside container
      targetPort: 4000 # pod's app port
      nodePort: 30800  # fixed NodePort on minikube
