apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - port: 4000       # inside cluster
      targetPort: 4000 # pod/container port
      nodePort: 3000   # external port on localhost
