apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  labels:
    app: ci-cd-app
spec:
  type: NodePort
  selector:
    app: ci-cd-app
  ports:
    - name: http
      port: 3000          # Service port
      targetPort: 3000    # Container port (where your Node.js server runs)
      nodePort: 30000     # External port - you can access via localhost:30000
      protocol: TCP